apiVersion: apps/v1
kind: Deployment
metadata:
  name: like-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: like-service
  template:
    metadata:
      labels:
        app: like-service
    spec:
      containers:
      - name: like
        image: shounak26/blogapp_microservices-like-service:latest
        ports:
        - containerPort: 5003
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: like-service
spec:
  selector:
    app: like-service
  ports:
    - port: 5003
      targetPort: 5003